version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
      # API version list for Android Docker image
      # https://hub.docker.com/r/circleci/android/tags
      # https://circleci.com/docs/2.0/circleci-images/#android
      # [was] - image: circleci/android:api-28
    #branches:
    #  only:
    #    - master
    resource_class: medium
    environment:
      JVM_OPTS: -Xmx5000m
    steps:
      - checkout
      #- restore_cache:
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: sdkmanager --licenses
      - run: yes | sdkmanager --update || exit 0
      - run:
          command: ./gradlew androidDependencies
          when: always
      #- save_cache:
      #    paths:
      #      - ~/.gradle
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Unit Tests against Presenter
          command: ./gradlew clean lint test jacocoTestReport
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/reports/tests/
      - run:
          name: Build apk
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - store_artifacts:
          path: ./app/build/outputs/apk/debug/app-debug.apk
          destination: /apks/app-debug.apk
      - store_artifacts:
          path: ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          destination: /apks/app-debug-androidTest.apk
